### ISSUE TITLE
"exceptions" or something else?

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/FAIR_wizard#102]
@tburdett @FuqiX @theisuru Going over the wizard, I was puzzled by this question:

![image](https://user-images.githubusercontent.com/517736/190383809-f2fe2c09-eac4-4cc7-9178-ef7ef11a638c.png)

Could it be a transcription error ? Do you mean "expectations" ? 

hth

P

**Comment by theisuru** [comment]
@proccaserra, Thanks for pointing this, @FuqiX is the data expert, but I also think it should be "expectations". I will fix it and deploy with the next release.

**Comment by nsjuty** [comment]
i actually read it as expectations ;)
