### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by theisuru** [FAIRplus/FAIR_wizard#18]
Search is case sensitive. When we search for EBiSC we have to be specific with case.

**Comment by FuqiX** [comment]
it seems the search function is not working, (not only cases). 
searching with "BridgeDb" returns 0 results

**Comment by theisuru** [comment]
Search is using labels for search. Since we are using RDF to search, I will look how we can search without case in RDF.

**Comment by theisuru** [comment]
Label search is not case sensitive anymore.
