### ISSUE TITLE
I don't have maven installed locally (and can't), can you give a dockerized version of that, too?

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/FAIR_wizard#19]
I don't have maven / java installed locally (and can't), can you give a dockerized version of that step, too?

Let me know if you need anything else, thanks! :)

**Comment by theisuru** [comment]
We can publish the docker image to a registry, so it can be run in local environment without building or even cloning this repository. Does this fit your requirements?

**Comment by robertgiessmann** [comment]
Yes, that would be great! Or maybe there is a maven docker as well?

**Comment by FuqiX** [comment]
the wizard can now be accessed here 45.88.80.100:8080 (the server ip might be changed in the future)
Closed due to inactivity.
