### ISSUE TITLE
in designed solution, all resources are presented in the network. display selected resource only

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#22]

**Comment by theisuru** [comment]
We do not have finalised process diagram for this to continue. Do we have a timeline for the process diagram.

**Comment by FuqiX** [comment]
Sorry, I was confused about this ticket. Can we say it's

**Comment by FuqiX** [comment]
@theisuru  Please find the updated FAIRification process diagram, and the updated solution layout here. https://docs.google.com/drawings/d/1NYsp5ffJS3ZbbzYhhOxBRf3WCgrKPceIWhFpAAE1oDw/edit?usp=sharing
