### ISSUE TITLE
fairification process: display the complete 11 step process all the time and allow users to select sub-processes.

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#36]
figure out how it should look like

**Comment by FuqiX** [comment]
example: https://docs.google.com/drawings/d/1TZdCj0Glh-k-FBxlniWcoO4n2mrPJpTHmX72B4il2jI/edit?usp=sharing

**Comment by theisuru** [comment]
Duplicate of #85

**Comment by FuqiX** [comment]
close because #85 is more up-to-date
