### ISSUE TITLE
hide irrelevant labels or more detailed label classifications

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#40]
currently we put everything in the label field. e.g. "cell line, unmapped, external, uc-tfas"

some should be separate attributes. others should be hidden from the resource card.

**Comment by theisuru** [comment]
It would be easier to show everyting in the label field and move other to different fields.

**Comment by theisuru** [comment]
We have `usecase` attribute for use case searches. Label search will also search for this field, and values would not be shown as a label in web.
`fw:usecase       ( "usecase_name" ) ;`

**Comment by FuqiX** [comment]
problem solved. new attributes will be created.
