### ISSUE TITLE
"relatesTo" tag not used in resource selection

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#42]
If one resource doesn't have the right label, but relates to another selected resource. Then it should also be prompted in the search results.

**Comment by theisuru** [comment]
This is done and needs to be tested. Correct functionlity depnds on #44

**Comment by FuqiX** [comment]
withthis data, tool-md5sum should be included in the search result but it doesn't seem to be the case.
 **http://localhost:8080/wizard?answers=Project%20manager&answers=Retrospective%20data&answers=No&answers=Interoperability&answers=Data%20validation**

<fw:Recipe-how-to-check-intactness-of-files-by-validating-checksums>
  fw:lastUpdate   "2021-06-30" ;
  fw:location     "https://fairplus.github.io/the-fair-cookbook/content/recipes/findability/checksum-validate.html" ;
  fw:name         "How to check intactness of files by validating checksums" ;
  fw:description "Confirming the identity of two different files may be achieved by calculating a so-called “checksum” of the file in the source system, calculating the checksum in the target system, and comparing the outputs.";
  fw:labels       ( "validation" "data sharing" ) ;
  fw:relatesTo    (<fw:Tool-md5sum>);
  fw:resourceType "Recipe" .

**Comment by theisuru** [comment]
@FuqiX  Which branch did you check? All the changes are in dev branch before merging to master. I can see the md5sum in search results.

**Comment by FuqiX** [comment]
problem solved!
