### ISSUE TITLE
adding assessment to the wizard

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#72]
**Aim:** 
we should allow people to _perform_ fair assessment to identify the needs. The wizard will then _use_ the result to find the right solutions. 

**Assessment template**
https://docs.google.com/spreadsheets/d/1vaRf4PXJ7FvxLZpIKXRIkiEYDSZP5ajsb3KnETz7Em0/edit#gid=685095937
Focusing on Sheet:Indicators. If we can also integrate information in the `Indicator details` tab, that would be even better. 

Each indicator in the spreadsheet has been imported as a FAIR wizard resource. And have the right labels.

- Option 1: display the table as a spreadsheet in the wizard page.
- Option 2: covert it to a survey, and display as a SurveyMonkey or a GoogleForm

Notes: 
- showing all 40 indicators might be overwhelming. One option is to group the indicators by F,A,I,R. Collapse the unselected groups and show them when they are activite.
- the indicator content might change in the future
- we might also import some automated fair assessment tools

**Comment by theisuru** [comment]
Initial assessment is added as a table. Indicators are grouped into F,A,I,R categories.
