### ISSUE TITLE
font problem in report generation 

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#87]
![image](https://user-images.githubusercontent.com/54043294/176907503-860ff1ea-b619-4e65-9b7d-0c4c6393224a.png)
This is very difficult to read

**Comment by theisuru** [comment]
I do not see blured fonts in my machine. Need to investigate further why this is happening. Did you use browser to view the PDF or is it pdf reader? what browser, reader are you using?

**Comment by FuqiX** [comment]
Thanks! It works fine with Chrome, but not with Firefox

**Comment by theisuru** [comment]
Works fine with my firefox version. I will check if I can use a common font thats available in all systems.

**Comment by theisuru** [comment]
@FuqiX  We were using TIMES_ROMAN and I changed to HELVETICA now. Could you check if it's better now. If there are further problems could you also let me know your firefox version.

**Comment by FuqiX** [comment]
this now works in my Firefox! Thanks! 
We might need to update the font to ensure the consistent styling across FAIRplus sites. but we can close it now
