### ISSUE TITLE
decision tree, add description to each answer. 

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/FAIR_wizard#9]
Some answers in the decision tree require  detailed descriptions. 
For example:

"Which role fits you best?"
"Data consumer (Bioinformatician who perform data analysis)" or "Software technician (e.g. Developers who build data manage systems)"

in this case, it would be nice to have a short answer only and provide a description (information in the parenthesis) separately, either with a hint box or in smaller fonts.

**Comment by FuqiX** [comment]
description has been added, but not displayed correctly

**Comment by theisuru** [comment]
Could you please explain this further. Do you expect differnt UI format or is there a bug showing description?

**Comment by FuqiX** [comment]
![Screenshot_2021-08-03_09-43-29](https://user-images.githubusercontent.com/54043294/128014963-24f3677a-7775-4207-aec5-9d2506a781a2.png)

there are description fields to each question and answer to support people understand the questions/answers. I am thinking a small hint button, providing such descriptions.

**Comment by FuqiX** [comment]
Tested. thanks!
